let students = [
  { id: 1, name: "Anil", age: 21, marks: 72, subject: "Math", grade: "B" },
  { id: 2, name: "Sneha", age: 20, marks: 88, subject: "English", grade: "A" },
  { id: 3, name: "Ravi", age: 22, marks: 33, subject: "Science", grade: "D" },
  { id: 4, name: "Pooja", age: 21, marks: 91, subject: "Math", grade: "A+" },
  { id: 5, name: "Sachin", age: 20, marks: 27, subject: "History", grade: "F" },
  { id: 6, name: "Meena", age: 23, marks: 64, subject: "English", grade: "C" },
  { id: 7, name: "Ajay", age: 21, marks: 80, subject: "Science", grade: "B+" },
  { id: 8, name: "Kavita", age: 22, marks: 55, subject: "History", grade: "C" },
  { id: 9, name: "Nikhil", age: 23, marks: 49, subject: "Math", grade: "C-" },
  {
    id: 10,
    name: "Bhavna",
    age: 20,
    marks: 76,
    subject: "English",
    grade: "B+",
  },
];

const employees = [
  {
    id: 1,
    name: "Alice",
    age: 30,
    department: "HR",
    salary: 50000,
    experience: 4,
  },
  {
    id: 2,
    name: "Bob",
    age: 45,
    department: "IT",
    salary: 75000,
    experience: 10,
  },
  {
    id: 3,
    name: "Charlie",
    age: 25,
    department: "Sales",
    salary: 40000,
    experience: 2,
  },
  {
    id: 4,
    name: "David",
    age: 35,
    department: "IT",
    salary: 80000,
    experience: 7,
  },
  {
    id: 5,
    name: "Eva",
    age: 29,
    department: "HR",
    salary: 55000,
    experience: 3,
  },
  {
    id: 6,
    name: "Frank",
    age: 50,
    department: "Finance",
    salary: 90000,
    experience: 20,
  },
  {
    id: 7,
    name: "Grace",
    age: 32,
    department: "Sales",
    salary: 47000,
    experience: 5,
  },
  {
    id: 8,
    name: "Henry",
    age: 28,
    department: "IT",
    salary: 67000,
    experience: 4,
  },
  {
    id: 9,
    name: "Ivy",
    age: 40,
    department: "Finance",
    salary: 72000,
    experience: 8,
  },
  {
    id: 10,
    name: "Jack",
    age: 38,
    department: "HR",
    salary: 60000,
    experience: 6,
  },
];

const products = [
  { id: 1, name: "Laptop", category: "Electronics", price: 75000, stock: 10 },
  { id: 2, name: "Phone", category: "Electronics", price: 35000, stock: 25 },
  { id: 3, name: "Fridge", category: "Appliances", price: 55000, stock: 8 },
  { id: 4, name: "Table", category: "Furniture", price: 15000, stock: 15 },
  { id: 5, name: "Microwave", category: "Appliances", price: 12000, stock: 5 },
];
